name: church_connect
description: "ChurchConnect - Welfare Ministry Mobile App for spiritual care and community management."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^12.1.3

  # UI Components
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^11.0.0

  # Database & Storage (MySQL via HTTP API)
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Authentication
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.1.6

  # Messaging & Communication
  firebase_messaging: ^14.7.9
  url_launcher: ^6.2.2

  # File & Media
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.1.0

  # Date & Time
  intl: ^0.19.0

  # Utilities
  uuid: ^4.2.1
  logger: ^2.0.2+1

  # CSV & Excel
  csv: ^5.0.2
  excel: ^4.0.2

  # Contacts
  contacts_service: ^0.6.3

  # Charts & Analytics
  fl_chart: ^0.66.0

  # Background Tasks
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
