// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVUMPLQY6Pcga1T8R3JRYFxkVB9wqRM1c',
    appId: '1:85337381939:web:b07d2c19d0de3b927a9746',
    messagingSenderId: '85337381939',
    projectId: 'church-connect-97bad',
    authDomain: 'church-connect-97bad.firebaseapp.com',
    storageBucket: 'church-connect-97bad.firebasestorage.app',
    measurementId: 'G-D396G9F1YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-okBOOaMn_w79wUOKtQDJrcX0dCDbebc',
    appId: '1:85337381939:android:e88d8e9d3d4430fb7a9746',
    messagingSenderId: '85337381939',
    projectId: 'church-connect-97bad',
    storageBucket: 'church-connect-97bad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCunY5jee-0yg024__QUGHB_bQQYtwhZLM',
    appId: '1:85337381939:ios:a9e86ea7c7c2dbb37a9746',
    messagingSenderId: '85337381939',
    projectId: 'church-connect-97bad',
    storageBucket: 'church-connect-97bad.firebasestorage.app',
    iosClientId: '85337381939-4009hrdo8i5ro75ueg35p7f8bq0ae6mr.apps.googleusercontent.com',
    iosBundleId: 'com.churchconnect.churchConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCunY5jee-0yg024__QUGHB_bQQYtwhZLM',
    appId: '1:85337381939:ios:a9e86ea7c7c2dbb37a9746',
    messagingSenderId: '85337381939',
    projectId: 'church-connect-97bad',
    storageBucket: 'church-connect-97bad.firebasestorage.app',
    iosClientId: '85337381939-4009hrdo8i5ro75ueg35p7f8bq0ae6mr.apps.googleusercontent.com',
    iosBundleId: 'com.churchconnect.churchConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVUMPLQY6Pcga1T8R3JRYFxkVB9wqRM1c',
    appId: '1:85337381939:web:bc31800e5ee912017a9746',
    messagingSenderId: '85337381939',
    projectId: 'church-connect-97bad',
    authDomain: 'church-connect-97bad.firebaseapp.com',
    storageBucket: 'church-connect-97bad.firebasestorage.app',
    measurementId: 'G-KSRTEZ51YW',
  );

}